
title = "Test for Hugo modules"


## To get build to work either:
#1. Remove module mount and reference in baseof
#2. Remove the CSS section in baseof.html

[module]
  [[module.mounts]]
    source = "./node_modules/lazysizes"
    target = "assets/npmplugins/lazysizes"
